#!/usr/bin/env node
// Regenerates the embedded font-metrics table (plan decision D5, section 5.4).
//
// This is an offline maintenance script in the mold of markdown-core's re2c
// outputs: the generated file is committed, and generation never runs during
// build or test. It reads only the vendored metrics snapshot next to it —
// no network, no node_modules.
//
//   node scripts/generate-metrics.mjs
//
// Values are emitted as 16.16 fixed-point fractions of the em so that the
// engine's layout arithmetic stays in integer scaled points and the canonical
// dump is byte-deterministic across platforms.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = join(root, "scripts", "metrics", "katex-font-metrics.json");
const targetPath = join(root, "packages", "tex-core", "core", "metrics.inc");

const snapshot = JSON.parse(readFileSync(sourcePath, "utf8"));
const { provenance, parameters, fonts } = snapshot;

// Row order is the txc_parameter enum order in metrics.h; the emitted
// count is static-asserted against the enum in metrics.c.
const parameterOrder = [
    "quad",
    "xHeight",
    "sup1",
    "sup2",
    "sup3",
    "sub1",
    "sub2",
    "supDrop",
    "subDrop",
    "defaultRuleThickness",
    "num1",
    "num2",
    "denom1",
    "denom2",
    "axisHeight"
];

const fixed = (value) => {
    const scaled = Math.round(value * 65536);
    if (!Number.isSafeInteger(scaled) || Math.abs(scaled) > 0x7fffffff) {
        throw new Error(`metric out of range: ${value}`);
    }
    return scaled;
};

const table = (font) => {
    const rows = Object.entries(fonts[font])
        .map(([codepoint, metric]) => ({ codepoint: Number(codepoint), metric }))
        .sort((left, right) => left.codepoint - right.codepoint);
    return rows
        .map(({ codepoint, metric }) => {
            const cp = `0x${codepoint.toString(16).toUpperCase().padStart(4, "0")}`;
            const fields = [fixed(metric.width), fixed(metric.height), fixed(metric.depth), fixed(metric.italic)];
            return `    {${cp}, ${fields.join(", ")}},`;
        })
        .join("\n");
};

const parameterTable = () => {
    if (!sameMembers(Object.keys(parameters), parameterOrder)) {
        throw new Error("snapshot parameters drifted from the emission order");
    }
    return parameterOrder
        .map((name) => {
            const columns = parameters[name];
            if (!Array.isArray(columns) || columns.length !== 3) {
                throw new Error(`parameter ${name} must carry exactly three size columns`);
            }
            return `    {${columns.map(fixed).join(", ")}}, /* ${name} */`;
        })
        .join("\n");
};
const sameMembers = (left, right) => left.length === right.length && right.every((value) => left.includes(value));

const output = `/* Generated by scripts/generate-metrics.mjs. DO NOT EDIT.
 *
 * Embedded glyph metrics for the default faces (plan decision D5): each row
 * is {codepoint, width, height, depth, italic} in 16.16 fixed-point em
 * units, sorted by codepoint for binary search.
 *
 * Source: ${provenance.package} ${provenance.version} ${provenance.file} (${provenance.license}),
 * vendored as scripts/metrics/katex-font-metrics.json (provenance and the
 * extracted subset are recorded there). The KaTeX metrics data describes the
 * Computer Modern faces; consumers may render with any visually compatible
 * font.
 */

/* Main-Regular: upright text and math face. */
static const txc_metric TXC_METRICS_UPRIGHT[] = {
${table("Main-Regular")}
};

/* Math-Italic: the math letter face. */
static const txc_metric TXC_METRICS_ITALIC[] = {
${table("Math-Italic")}
};

/* Style parameters (the TeXbook Appendix G sigmas and xis, via KaTeX
 * ${provenance.parametersFile}): rows in txc_parameter order, columns in
 * txc_mathsize order (text, script, scriptscript), each value an em
 * fraction of that size's own font. */
static const int32_t TXC_PARAMETERS[][3] = {
${parameterTable()}
};
`;

writeFileSync(targetPath, output);
console.log(`wrote ${targetPath}`);
